package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import tools.Util;

/**
 * ClienteOtb generated by hbm2java
 */
@Entity
@Table(name = "clienteotb",
         catalog = "db_guilherminososterberg"
)
public class ClienteOtb implements java.io.Serializable {

    private int idClienteOtb;
    private UsuarioOtb usuariootb;
    private String nomeOtb;
    private String sobreNomeOtb;
    private String cpfotb;
    private String enderecoOtb;
    private String paisOtb;
    private String bairroOtb;
    private String cidadeOtb;
    private String telefoneOtb;
    private String celularOtb;

    public ClienteOtb() {
    }

    public ClienteOtb(int idClienteOtb, UsuarioOtb usuariootb, String nomeOtb, String sobreNomeOtb, String cpfotb, String enderecoOtb, String paisOtb, String bairroOtb, String cidadeOtb, String telefoneOtb, String celularOtb) {
        this.idClienteOtb = idClienteOtb;
        this.usuariootb = usuariootb;
        this.nomeOtb = nomeOtb;
        this.sobreNomeOtb = sobreNomeOtb;
        this.cpfotb = cpfotb;
        this.enderecoOtb = enderecoOtb;
        this.paisOtb = paisOtb;
        this.bairroOtb = bairroOtb;
        this.cidadeOtb = cidadeOtb;
        this.telefoneOtb = telefoneOtb;
        this.celularOtb = celularOtb;
    }

    public ClienteOtb(int idClienteOtb, UsuarioOtb usuariootb, String nomeOtb, String sobreNomeOtb, String cpfotb, String enderecoOtb, String paisOtb, String bairroOtb, String cidadeOtb, String telefoneOtb, String celularOtb, Set comprasotbs) {
        this.idClienteOtb = idClienteOtb;
        this.usuariootb = usuariootb;
        this.nomeOtb = nomeOtb;
        this.sobreNomeOtb = sobreNomeOtb;
        this.cpfotb = cpfotb;
        this.enderecoOtb = enderecoOtb;
        this.paisOtb = paisOtb;
        this.bairroOtb = bairroOtb;
        this.cidadeOtb = cidadeOtb;
        this.telefoneOtb = telefoneOtb;
        this.celularOtb = celularOtb;
    }

    @Id

    @Column(name = "IdClienteOTB", unique = true, nullable = false)
    public int getIdClienteOtb() {
        return this.idClienteOtb;
    }

    public void setIdClienteOtb(int idClienteOtb) {
        this.idClienteOtb = idClienteOtb;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Fk_UsuarioOTB", nullable = false)
    public UsuarioOtb getUsuariootb() {
        return this.usuariootb;
    }

    public void setUsuariootb(UsuarioOtb usuariootb) {
        this.usuariootb = usuariootb;
    }

    @Column(name = "NomeOTB", nullable = false, length = 45)
    public String getNomeOtb() {
        return this.nomeOtb;
    }

    public void setNomeOtb(String nomeOtb) {
        this.nomeOtb = nomeOtb;
    }

    @Column(name = "SobreNomeOTB", nullable = false, length = 45)
    public String getSobreNomeOtb() {
        return this.sobreNomeOtb;
    }

    public void setSobreNomeOtb(String sobreNomeOtb) {
        this.sobreNomeOtb = sobreNomeOtb;
    }

    @Column(name = "CPFOTB", nullable = false, length = 45)
    public String getCpfotb() {
        return this.cpfotb;
    }

    public void setCpfotb(String cpfotb) {
        this.cpfotb = cpfotb;
    }

    @Column(name = "EnderecoOTB", nullable = false, length = 45)
    public String getEnderecoOtb() {
        return this.enderecoOtb;
    }

    public void setEnderecoOtb(String enderecoOtb) {
        this.enderecoOtb = enderecoOtb;
    }

    @Column(name = "PaisOTB", nullable = false, length = 45)
    public String getPaisOtb() {
        return this.paisOtb;
    }

    public void setPaisOtb(String paisOtb) {
        this.paisOtb = paisOtb;
    }

    @Column(name = "BairroOTB", nullable = false, length = 45)
    public String getBairroOtb() {
        return this.bairroOtb;
    }

    public void setBairroOtb(String bairroOtb) {
        this.bairroOtb = bairroOtb;
    }

    @Column(name = "CidadeOTB", nullable = false, length = 45)
    public String getCidadeOtb() {
        return this.cidadeOtb;
    }

    public void setCidadeOtb(String cidadeOtb) {
        this.cidadeOtb = cidadeOtb;
    }

    @Column(name = "TelefoneOTB", nullable = false, length = 45)
    public String getTelefoneOtb() {
        return this.telefoneOtb;
    }

    public void setTelefoneOtb(String telefoneOtb) {
        this.telefoneOtb = telefoneOtb;
    }

    @Column(name = "CelularOTB", nullable = false, length = 45)
    public String getCelularOtb() {
        return this.celularOtb;
    }

    public void setCelularOtb(String celularOtb) {
        this.celularOtb = celularOtb;
    }

    @Override
    public String toString() {
        return nomeOtb;
    }

}
