package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * ComprasOtb generated by hbm2java
 */
@Entity
@Table(name="comprasotb"
    ,catalog="db_guilherminososterberg"
)
public class ComprasOtb  implements java.io.Serializable {


     private int idComprasOtb;
     private ClienteOtb clienteotb;
     private FornecedorOtb fornecedorotb;
     private Date dataComprasOtb;
     private Double totalotb;

    public ComprasOtb() {
    }

	
    public ComprasOtb(int idComprasOtb, ClienteOtb clienteotb, FornecedorOtb fornecedorotb, Date dataComprasOtb, Double totalotb) {
        this.idComprasOtb = idComprasOtb;
        this.clienteotb = clienteotb;
        this.fornecedorotb = fornecedorotb;
        this.dataComprasOtb = dataComprasOtb;
        this.totalotb = totalotb;
    }
    public ComprasOtb(int idComprasOtb, ClienteOtb clienteotb, FornecedorOtb fornecedorotb, Date dataComprasOtb, Double totalotb, Set comprasprodutosotbs) {
       this.idComprasOtb = idComprasOtb;
       this.clienteotb = clienteotb;
       this.fornecedorotb = fornecedorotb;
       this.dataComprasOtb = dataComprasOtb;
       this.totalotb = totalotb;
    }
   
     @Id 

    
    @Column(name="IdComprasOTB", unique=true, nullable=false)
    public int getIdComprasOtb() {
        return this.idComprasOtb;
    }
    
    public void setIdComprasOtb(int idComprasOtb) {
        this.idComprasOtb = idComprasOtb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Fk_ClienteOTB", nullable=false)
    public ClienteOtb getClienteotb() {
        return this.clienteotb;
    }
    
    public void setClienteotb(ClienteOtb clienteotb) {
        this.clienteotb = clienteotb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Fk_FornecedorOTB", nullable=false)
    public FornecedorOtb getFornecedorotb() {
        return this.fornecedorotb;
    }
    
    public void setFornecedorotb(FornecedorOtb fornecedorotb) {
        this.fornecedorotb = fornecedorotb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataComprasOTB", nullable=false, length=10)
    public Date getDataComprasOtb() {
        return this.dataComprasOtb;
    }
    
    public void setDataComprasOtb(Date dataComprasOtb) {
        this.dataComprasOtb = dataComprasOtb;
    }

    
    @Column(name="TotalOTB", nullable=true, precision=11)
    public Double getTotalotb() {
        return this.totalotb;
    }
    
    public void setTotalotb(Double totalotb) {
        this.totalotb = totalotb;
    }

    @Override
    public String toString() {
        return (Util.doubleStr(idComprasOtb));
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof ComprasOtb) {
            ComprasOtb comprasotb = (ComprasOtb) object;
            if (this.getIdComprasOtb() == comprasotb.getIdComprasOtb());
            {
                return true;
            }
        }
        return false;

    }
}


