package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComprasProdutosOtb generated by hbm2java
 */
@Entity
@Table(name="comprasprodutosotb"
    ,catalog="db_guilherminososterberg"
)
public class ComprasProdutosOtb  implements java.io.Serializable {


     private int idComprasProdutosOtb;
     private ComprasOtb comprasotb;
     private ProdutoOtb produtootb;
     private String quantidadeOtb;
     private Double valorUnidadeOtb;
     private Double totalOtb;

    public ComprasProdutosOtb() {
    }

    public ComprasProdutosOtb(int idComprasProdutosOtb,ComprasOtb comprasotb, ProdutoOtb produtootb, String quantidadeOtb, Double valorUnidadeOtb, Double totalOtb) {
       this.idComprasProdutosOtb = idComprasProdutosOtb;
       this.comprasotb = comprasotb;
       this.produtootb = produtootb;
       this.quantidadeOtb = quantidadeOtb;
       this.valorUnidadeOtb = valorUnidadeOtb;
       this.totalOtb = totalOtb;
    }
   
     @Id 

    
    @Column(name="IdComprasProdutosOTB", unique=true, nullable=false)
    public int getIdComprasProdutosOtb() {
        return this.idComprasProdutosOtb;
    }
    
    public void setIdComprasProdutosOtb(int idComprasProdutosOtb) {
        this.idComprasProdutosOtb = idComprasProdutosOtb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Fk_ComprasOTB", nullable=false)
    public ComprasOtb getComprasotb() {
        return this.comprasotb;
    }
    
    public void setComprasotb (ComprasOtb comprasotb) {
        this.comprasotb = comprasotb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Fk_ProdutosOTB", nullable=false)
    public ProdutoOtb getProdutootb() {
        return this.produtootb;
    }
    
    public void setProdutootb(ProdutoOtb produtootb) {
        this.produtootb = produtootb;
    }

    
    @Column(name="QuantidadeOTB", nullable=false, length=45)
    public String getQuantidadeOtb() {
        return this.quantidadeOtb;
    }
    
    public void setQuantidadeOtb(String quantidadeOtb) {
        this.quantidadeOtb = quantidadeOtb;
    }

    
    @Column(name="ValorUnidadeOTB", nullable=false, precision=11)
    public Double getValorUnidadeOtb() {
        return this.valorUnidadeOtb;
    }
    
    public void setValorUnidadeOtb(Double valorUnidadeOtb) {
        this.valorUnidadeOtb = valorUnidadeOtb;
    }

    
    @Column(name="TotalOTB", nullable=false, precision=11)
    public Double getTotalOtb() {
        return this.totalOtb;
    }
    
    public void setTotalOtb(Double totalOtb) {
        this.totalOtb = totalOtb;
    }




}


