package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * FornecedorOtb generated by hbm2java
 */
@Entity
@Table(name="fornecedorotb"
    ,catalog="db_guilherminososterberg"
)
public class FornecedorOtb  implements java.io.Serializable {


     private int idFornecedorOtb;
     private UsuarioOtb usuariootb;
     private String nomeOtb;
     private String cpfotb;
     private Date dataNascOtb;

    public FornecedorOtb() {
    }

	
    public FornecedorOtb(int idFornecedorOtb, UsuarioOtb usuariootb, String nomeOtb, String cpfotb, Date dataNascOtb) {
        this.idFornecedorOtb = idFornecedorOtb;
        this.usuariootb = usuariootb;
        this.nomeOtb = nomeOtb;
        this.cpfotb = cpfotb;
        this.dataNascOtb = dataNascOtb;
    }
    public FornecedorOtb(int idFornecedorOtb, UsuarioOtb usuariootb, String nomeOtb, String cpfotb, Date dataNascOtb, Set comprasotbs) {
       this.idFornecedorOtb = idFornecedorOtb;
       this.usuariootb = usuariootb;
       this.nomeOtb = nomeOtb;
       this.cpfotb = cpfotb;
       this.dataNascOtb = dataNascOtb;
    }
   
     @Id 

    
    @Column(name="IdFornecedorOTB", unique=true, nullable=false)
    public int getIdFornecedorOtb() {
        return this.idFornecedorOtb;
    }
    
    public void setIdFornecedorOtb(int idFornecedorOtb) {
        this.idFornecedorOtb = idFornecedorOtb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Fk_UsuarioOTB", nullable=false)
    public UsuarioOtb getUsuariootb() {
        return this.usuariootb;
    }
    
    public void setUsuariootb(UsuarioOtb usuariootb) {
        this.usuariootb = usuariootb;
    }

    
    @Column(name="NomeOTB", nullable=false, length=45)
    public String getNomeOtb() {
        return this.nomeOtb;
    }
    
    public void setNomeOtb(String nomeOtb) {
        this.nomeOtb = nomeOtb;
    }

    
    @Column(name="CPFOTB", nullable=false, length=45)
    public String getCpfotb() {
        return this.cpfotb;
    }
    
    public void setCpfotb(String cpfotb) {
        this.cpfotb = cpfotb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataNascOTB", nullable=false, length=10)
    public Date getDataNascOtb() {
        return this.dataNascOtb;
    }
    
    public void setDataNascOtb(Date dataNascOtb) {
        this.dataNascOtb = dataNascOtb;
    }
    
    @Override
    public String toString() {
        return (Util.doubleStr(idFornecedorOtb)) + " " + nomeOtb;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof FornecedorOtb) {
            FornecedorOtb fornecedorotb = (FornecedorOtb) object;
            if (this.getIdFornecedorOtb() == fornecedorotb.getIdFornecedorOtb());
            {
                return true;
            }
        }
        return false;

    }



}


