package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import tools.Util;

/**
 * ProdutoOtb generated by hbm2java
 */
@Entity
@Table(name="produtootb"
    ,catalog="db_guilherminososterberg"
)
public class ProdutoOtb  implements java.io.Serializable {


     private int idProdutoOtb;
     private String nomeOtb;
     private Double precoOtb;
     private String estoqueOtb;
     private String marca;
     private Set comprasprodutosotbs = new HashSet(0);

    public ProdutoOtb() {
    }

	
    public ProdutoOtb(int idProdutoOtb, String nomeOtb, Double precoOtb, String estoqueOtb, String marca) {
        this.idProdutoOtb = idProdutoOtb;
        this.nomeOtb = nomeOtb;
        this.precoOtb = precoOtb;
        this.estoqueOtb = estoqueOtb;
        this.marca = marca;
    }
    public ProdutoOtb(int idProdutoOtb, String nomeOtb, Double precoOtb, String estoqueOtb, String marca, Set comprasprodutosotbs) {
       this.idProdutoOtb = idProdutoOtb;
       this.nomeOtb = nomeOtb;
       this.precoOtb = precoOtb;
       this.estoqueOtb = estoqueOtb;
       this.marca = marca;
       this.comprasprodutosotbs = comprasprodutosotbs;
    }
   
     @Id 

    
    @Column(name="idProdutoOTB", unique=true, nullable=false)
    public int getIdProdutoOtb() {
        return this.idProdutoOtb;
    }
    
    public void setIdProdutoOtb(int idProdutoOtb) {
        this.idProdutoOtb = idProdutoOtb;
    }

    
    @Column(name="NomeOTB", nullable=false, length=45)
    public String getNomeOtb() {
        return this.nomeOtb;
    }
    
    public void setNomeOtb(String nomeOtb) {
        this.nomeOtb = nomeOtb;
    }

    
    @Column(name="PrecoOTB", nullable=false, precision=11)
    public Double getPrecoOtb() {
        return this.precoOtb;
    }
    
    public void setPrecoOtb(Double precoOtb) {
        this.precoOtb = precoOtb;
    }

    
    @Column(name="EstoqueOTB", nullable=false, length=45)
    public String getEstoqueOtb() {
        return this.estoqueOtb;
    }
    
    public void setEstoqueOtb(String estoqueOtb) {
        this.estoqueOtb = estoqueOtb;
    }

    
    @Column(name="Marca", nullable=false, length=45)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produtootb")
    public Set getComprasprodutosotbs() {
        return this.comprasprodutosotbs;
    }
    
    public void setComprasprodutosotbs(Set comprasprodutosotbs) {
        this.comprasprodutosotbs = comprasprodutosotbs;
    }

        @Override
    public String toString() {
        return (Util.doubleStr(idProdutoOtb)) + " " + nomeOtb;
    } // O método toString() é usado para fornecer uma representação em forma de string do objeto.

    @Override
    public boolean equals(Object object) {
        if (object instanceof ProdutoOtb) {
            ProdutoOtb produtoOtb = (ProdutoOtb) object;
            if (this.getIdProdutoOtb() == produtoOtb.getIdProdutoOtb()); 
            {
                return true;
            }
        }
        return false;
    }


}


