package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * UsuarioOtb generated by hbm2java
 */
@Entity
@Table(name="usuariootb"
    ,catalog="db_guilherminososterberg"
)
public class UsuarioOtb  implements java.io.Serializable {


     private int idUsuarioOtb;
     private String nomeOtb;
     private String apelidoOtb;
     private String cpfotb;
     private Date dataNascOtb;
     private String senhaOtb;
     private char ativo;
     private int nivel;

    public UsuarioOtb() {
    }

	
    public UsuarioOtb(int idUsuarioOtb, String nomeOtb, String apelidoOtb, String cpfotb, Date dataNascOtb, String senhaOtb, char ativo, int nivel) {
        this.idUsuarioOtb = idUsuarioOtb;
        this.nomeOtb = nomeOtb;
        this.apelidoOtb = apelidoOtb;
        this.cpfotb = cpfotb;
        this.dataNascOtb = dataNascOtb;
        this.senhaOtb = senhaOtb;
        this.ativo = ativo;
        this.nivel = nivel;
    }
    public UsuarioOtb(int idUsuarioOtb, String nomeOtb, String apelidoOtb, String cpfotb, Date dataNascOtb, String senhaOtb, char ativo, int nivel, Set fornecedorotbs, Set clienteotbs) {
       this.idUsuarioOtb = idUsuarioOtb;
       this.nomeOtb = nomeOtb;
       this.apelidoOtb = apelidoOtb;
       this.cpfotb = cpfotb;
       this.dataNascOtb = dataNascOtb;
       this.senhaOtb = senhaOtb;
       this.ativo = ativo;
       this.nivel = nivel;
    }
   
     @Id 

    
    @Column(name="IdUsuarioOTB", unique=true, nullable=false)
    public int getIdUsuarioOtb() {
        return this.idUsuarioOtb;
    }
    
    public void setIdUsuarioOtb(int idUsuarioOtb) {
        this.idUsuarioOtb = idUsuarioOtb;
    }

    
    @Column(name="NomeOTB", nullable=false, length=45)
    public String getNomeOtb() {
        return this.nomeOtb;
    }
    
    public void setNomeOtb(String nomeOtb) {
        this.nomeOtb = nomeOtb;
    }

    
    @Column(name="ApelidoOTB", nullable=false, length=45)
    public String getApelidoOtb() {
        return this.apelidoOtb;
    }
    
    public void setApelidoOtb(String apelidoOtb) {
        this.apelidoOtb = apelidoOtb;
    }

    
    @Column(name="CPFOTB", nullable=false, length=45)
    public String getCpfotb() {
        return this.cpfotb;
    }
    
    public void setCpfotb(String cpfotb) {
        this.cpfotb = cpfotb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DataNascOTB", nullable=false, length=10)
    public Date getDataNascOtb() {
        return this.dataNascOtb;
    }
    
    public void setDataNascOtb(Date dataNascOtb) {
        this.dataNascOtb = dataNascOtb;
    }

    
    @Column(name="SenhaOTB", nullable=false, length=45)
    public String getSenhaOtb() {
        return this.senhaOtb;
    }
    
    public void setSenhaOtb(String senhaOtb) {
        this.senhaOtb = senhaOtb;
    }

    
    @Column(name="Ativo", nullable=false, length=1)
    public char getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(char ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="Nivel", nullable=false)
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    
    @Override
    public String toString() {
        return (Util.doubleStr(idUsuarioOtb))  +  " "  + nomeOtb;
    } // O método toString() é usado para fornecer uma representação em forma de string do objeto.

    @Override
    public boolean equals(Object object) {
        if (object instanceof UsuarioOtb) {
            UsuarioOtb usuarioOtb = (UsuarioOtb) object;
            if (this.getIdUsuarioOtb() == usuarioOtb.getIdUsuarioOtb()); 
            {
                return true;
            }
        }
        return false;
    }




}


