package BEAN;
// Generated 24/11/2025 23:34:24 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * UsuarioOtb generated by hbm2java
 */
@Entity
@Table(name = "usuariootb",
         catalog = "db_guilherminososterberg"
)
public class UsuarioOtb implements java.io.Serializable {

    private int idUsuarioOtb;
    private String nomeOtb;
    private String apelidoOtb;
    private String cpfOtb;
    private Date dataNascOTB;
    private String senhaOtb;
    private String ativo;
    private int nivel;

    public UsuarioOtb() {
    }

    public UsuarioOtb(int idUsuarioOtb, String nomeOtb, String apelidoOtb, String cpfOtb, Date dataNascOTB, String senhaOtb, String ativo, int nivel) {
        this.idUsuarioOtb = idUsuarioOtb;
        this.nomeOtb = nomeOtb;
        this.apelidoOtb = apelidoOtb;
        this.cpfOtb = cpfOtb;
        this.dataNascOTB = dataNascOTB;
        this.senhaOtb = senhaOtb;
        this.ativo = ativo;
        this.nivel = nivel;
    }

    public UsuarioOtb(int idUsuarioOtb, String nomeOtb, String apelidoOtb, String cpfotb, Date dataNascOTB, String senhaOtb, String ativo, int nivel, Set fornecedorotbs, Set clienteotbs) {
        this.idUsuarioOtb = idUsuarioOtb;
        this.nomeOtb = nomeOtb;
        this.apelidoOtb = apelidoOtb;
        this.cpfOtb = cpfotb;
        this.dataNascOTB = dataNascOTB;
        this.senhaOtb = senhaOtb;
        this.ativo = ativo;
        this.nivel = nivel;
    }

    @Id

    @Column(name = "IdUsuarioOtb", unique = true, nullable = false)
    public int getIdUsuarioOtb() {
        return this.idUsuarioOtb;
    }

    public void setIdUsuarioOtb(int idUsuarioOtb) {
        this.idUsuarioOtb = idUsuarioOtb;
    }

    @Column(name = "NomeOTB", nullable = false, length = 45)
    public String getNomeOtb() {
        return this.nomeOtb;
    }

    public void setNomeOtb(String nomeOtb) {
        this.nomeOtb = nomeOtb;
    }

    @Column(name = "ApelidoOTB", nullable = false, length = 45)
    public String getApelidoOtb() {
        return this.apelidoOtb;
    }

    public void setApelidoOtb(String apelidoOtb) {
        this.apelidoOtb = apelidoOtb;
    }

    @Column(name = "CPFOTB", nullable = false, length = 45)
    public String getCpfOtb() {
        return this.cpfOtb;
    }

    public void setCpfOtb(String cpfOtb) {
        this.cpfOtb = cpfOtb;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DataNascOtb", nullable = false, length = 10)
    public Date getDataNascOtb() {
        return this.dataNascOTB;
    }

    public void setDataNascOtb(Date dataNascOTB) {
        this.dataNascOTB = dataNascOTB;
    }

    @Column(name = "SenhaOTB", nullable = false, length = 45)
    public String getSenhaOtb() {
        return this.senhaOtb;
    }

    public void setSenhaOtb(String senhaOtb) {
        this.senhaOtb = senhaOtb;
    }

    @Column(name = "Ativo", nullable = false, length = 1)
    public String getAtivo() {
        return this.ativo;
    }

    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }

    @Column(name = "Nivel", nullable = false)
    public int getNivel() {
        return this.nivel;
    }

    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    @Override
    public String toString() {
        return nomeOtb;
    }

}
